### ISSUE TITLE
Running TensorSV in inference mode

### ISSUE THREAD

**Issue by fcunial** [timothyjamesbecker/TensorSV#1]
I tried running TensorSV purely in inference mode, but I encountered several errors that I was not able to circumvent.

I have an environment set up as described in the GitHub readme, with all the correct versions. I'm working with a BAM file that contains reads aligned just to human chromosome 22, and I use a reference file that contains just chromosome 22. As required by ``hfm``, I made sure that the BAM contains an ``@RG`` line in the header, with ID and SM entries: 
```
@RG     ID:DUMMYSAMPLE  SM:DUMMYSAMPLE 
```
and I made sure that the BAM contains an ``RG`` tag for every BAM record, identifying the record as coming from the same group.

I followed the 4-step procedure in the readme. Running ``extractor.py`` at the first step succeeds, creating the expected ``.merged.hdf5`` file in the output directory. But in the following steps I met errors that I tried to circumvent (without success) by following the two alternative strategies outlined below (I also tried to run the tool on a whole-genome BAM and on a whole-genome reference, but I encountered unsormountable errors of similar nature).

### Strategy 1

As described in the readme, I pip installed ``tensorsv-0.0.1`` and I ran ``data_prep.py``, without specifying the ``--vcf_in_path`` argument, since I'm running in inference mode and there is no VCF to supply. I got the following error:

```
hfm_sms=['alignments-with-args-and-sm']
vcf_sms=[]
sms=['alignments-with-args-and-sm']
preparing target files from maxima, ref and vcf input files...
getting maxima sm=output_dir_ISSUE/alignments-with-args-and-sm.merged.hdf5
generating maxima ranges for alignments-with-args-and-sm.merged.hdf5
completed maxima regions in 0.61 sec
Traceback (most recent call last):
  File "~/.conda/envs/tensorsv_env/bin/data_prep.py", line 1331, in <module>
    with open(vcf_in_dir+'/sms.maxima.json','r') as f: mask = json.load(f)
FileNotFoundError: [Errno 2] No such file or directory: '/sms.maxima.json'
```

The code is asking for a nonexistent file in the root of the filesystem. Thus, I tried setting the ``--vcf_in_path`` argument to the same directory as ``--hfm_in_path``, but I got exactly the same error, since that directory does not contain the required json file. Thus, I added a blank ``sms.maxima.json`` file (that contains just ``{}``) to the ``--vcf_in_path`` directory, and I got the following new error:

```
hfm_sms=['alignments-with-args-and-sm']
vcf_sms=[]
sms=['alignments-with-args-and-sm']
preparing target files from maxima, ref and vcf input files...
Traceback (most recent call last):
  File "~/.conda/envs/tensorsv_env/bin/data_prep.py", line 1332, in <module>
    with open(vcf_in_dir+'/ref.meta.json','r') as f:   seqs = json.load(f)
FileNotFoundError: [Errno 2] No such file or directory: './output_dir/ref.meta.json'
```

I then tried adding the required ``ref.meta.json`` (another blank json that contains just ``{}``) to the corresponding directory, but I got a different error:

```
hfm_sms=['alignments-with-args-and-sm']
vcf_sms=[]
sms=['alignments-with-args-and-sm']
preparing target files from maxima, ref and vcf input files...
Traceback (most recent call last):
  File "~/.conda/envs/tensorsv_env/bin/data_prep.py", line 1334, in <module>
    raise IOError
OSError
```

Looking at the code of the pip-installed ``data_prep.py`` at line 1334, it seems to me that this IOError is raised unconditionally (!). Interestingly, the ``raise`` instruction at that line is not present in the latest version of the code on GitHub, so I tried commenting it out. But I got yet another error:

```
hfm_sms=['alignments-with-args-and-sm']
vcf_sms=[]
sms=['alignments-with-args-and-sm']
preparing target files from maxima, ref and vcf input files...
using default g1kp3 vcf format conversions
generating new dict pickle from vcf input...
incorrect vcf file suffix...
Traceback (most recent call last):
  File "~/.conda/envs/tensorsv_env/bin/data_prep.py", line 1352, in <module>
    D = g1kp3_vcf_to_dict(vcf_path=vcf_in_path,out_path=vcf_in_dir,samples=hfm_sms)
  File "~/.conda/envs/tensorsv_env/bin/data_prep.py", line 40, in g1kp3_vcf_to_dict
    while s[-1]=='\n': s = s[:-1] #clean up any loose '\n'
IndexError: string index out of range 
```

This is where I decided to give up.

### Strategy 2

I observed that the code in the repository is more recent than the code in the pip package (version 0.1.0 and 0.0.1, respectively), thus I cloned the repository and I ran ``data_prep.py`` again, this time using the Python file from the cloned repo. Once again, I did not specify the ``--vcf_in_path`` argument, since I'm running purely in inference mode. This time the program completed successfully, creating a ``.norm.hdf5`` file in a newly generated ``tensors`` subdirectory.

Since I'm interested only in the inference mode, I skipped the ``train_sv.py`` step and I ran the ``predict_sv.py`` file from the cloned repo, setting:

``--base_dir`` to the parent directory of the ``tensors`` directory that contains the normalized ``.norm.hdf5`` file;

``--run_dir`` to the parent directory of the ``models`` directory that contains the pretrained model files in the GitHub repo;

``--samples`` to the sample ID that I added to the BAM at the beginning;

``--seqs`` to 22;

``--sv_type`` to ``DEL``.

But I got the following error:

```
working on sv=DEL
Traceback (most recent call last):
  File "./TensorSV/bin/predict_sv.py", line 1182, in <module>
    with open(score_path,'r') as sf: score_data = json.load(sf)
FileNotFoundError: [Errno 2] No such file or directory: './TensorSV/tensorsv//test/scores/all-DEL-L.score.json'
```

The program is asking for a ``.score.json`` file, which I'm unable to find anywhere in the GitHub repo. This is where I decided to give up.

**Comment by timothyjamesbecker** [comment]
Lets first start with the basics. Data has to be processed in a specific way and your folders have to be set up in  a specific way as well. To start you first generate the hfm summaries with have the *merged.hdf5 suffix.  After that what you are doing with data_prep.py is normalizing your data and then packaging it as tensorflow tensors. In order to do that you need to generate the reference meta data which doesn't seem to be happening for you.  You can not simply skip generation of the sms.maxima,json and ref.meta.json files they will cause all of the rest of the analysis to not work!  I am closing this issue, since what needs to happen is that you first need to provide the hfm parameters used to generate the hfm file.  After that you would nee to provide the parameters you used for the data_prep.py step which is failing.  After we find the issue there, you can proceed to move forward with the analysis and again you will need to provide your command lines if you are encountering an issue. Ideally it needs to be repeatable. The last information thing to note is that if you would like to do inference mode you need to download one of the pre-trained models.  They are in the realease sections and you can currently pick from a randomly generated germline or somatic model built using the somax framework.

**Comment by fcunial** [comment]
Thanks for your reply. [Here is a package (1.5 GB)](https://www.dropbox.com/s/3dhkle9yl547jw8/tensorsv_issue.tar.gz?dl=0) that should contain all the files needed for reproducing the errors. Assume that you are in the directory that contains the files you downloaded, and assume that directory `./TensorSV` is a clone of the repo. Then the command lines I used are:

For Strategy 1 above:
```
extractor.py --ref_path ./hg19_chr22.fa --in_path ./ --out_dir ./output_dir_ISSUE --seqs 22 --window 25 --branch 2 --cpus 1

data_prep.py --hfm_in_path ./output_dir_ISSUE --out_path ./output_dir_ISSUE --cpus 1
```

For Strategy 2 I did the same, but I used the Python scripts inside the cloned repo:
```
extractor.py --ref_path ./hg19_chr22.fa --in_path ./ --out_dir ./output_dir_ISSUE --seqs 22 --window 25 --branch 2 --cpus 1

python ./TensorSV/bin/data_prep.py --hfm_in_path ./output_dir_ISSUE --out_path ./output_dir_ISSUE --cpus 1

python ./TensorSV/bin/predict_sv.py --base_dir ./output_dir_ISSUE/ --run_dir ./TensorSV/tensorsv/ --out_dir ./output_dir_ISSUE/ --samples DUMMYSAMPLE --sv_type DEL --seqs 22 --gpu_num 0
```

**Comment by timothyjamesbecker** [comment]
You may imagine that as primary author and software developer for several open source projects, it is important to prioritize time helping the community of researchers that would like to use these tools for analysis as oppose to simply working toward a competing method.  As a professional courtesy going forward you should state your affiliation and intent.  In your case it seems you have unpublished work that you would like to compare the HFM/TensorSV framework against (based on your https://www.biorxiv.org/ preprint). You can follow the citations and author contacts on this github page to directly email me for user support.  I will provide you will a well established human CRAM file URL and fasta reference and then the exact command lines that will provide a functional output.  Getting your own data to work with the framework will be an exercise for you to complete.

Best wishes,

-TJB
